name: "ci and cd"

on: [push]

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: install deps
          run: npm install

        - name: run front-end
          run: npm run dev

  cd:
    needs: ci
    steps: 
        - name: install deps
          run: npm install
        
        - run: npm run build
        